//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_Diff_Checker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Git_Diff_Checker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children of the sun, see your time has just begun, searching for your ways, through adventures every day. 
        ///Every day and night, with the condor in flight, with all your friends in tow, you search for the Cities of Gold.
        /// Ah-ah-ah-ah-ah… wishing for The Cities of Gold.
        /// Ah-ah-ah-ah-ah… some day we will find The Cities of Gold. 
        ///Do-do-do-do ah-ah-ah, do-do-do-do, Cities of Gold. Do-do-do-do, Cities of Gold. 
        ///Ah-ah-ah-ah-ah… some day we will find The Cities of Gold. .
        /// </summary>
        internal static string file1 {
            get {
                return ResourceManager.GetString("file1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One for all and all for one, Muskehounds are always ready. 
        ///One for all and all for one, helping everybody. 
        ///One for all and all for one, it’s a pretty story. 
        ///Sharing everything with fun, that’s the way to be. 
        ///One for all and all for one, Muskehounds are always ready. 
        ///One for all and all for one, helping everybody. One for all and all for one, can sound pretty corny. 
        ///If you’ve got a problem chum, think how it could be. .
        /// </summary>
        internal static string file2 {
            get {
                return ResourceManager.GetString("file2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children of the sun, see your time has just begun, searching for your ways, through adventures every day. 
        ///Every day and night, with the condor in flight, with all your friends in tow, you search for the Cities of Gold.
        /// Ah-ah-ah-ah-ah… wishing for The Cities of Gold.
        /// Ah-ah-ah-ah-ah… some day we will find The Cities of Gold. 
        ///Do-do-do-do ah-ah-ah, do-do-do-do, Cities of Gold. Do-do-do-do, Cities of Gold. 
        ///Ah-ah-ah-ah-ah… some day we will find The Cities of Gold. .
        /// </summary>
        internal static string file3 {
            get {
                return ResourceManager.GetString("file3", resourceCulture);
            }
        }
    }
}
